apiVersion: v1
name: mxnet
version: 1.4.30
appVersion: 1.7.0
description: A flexible and efficient library for deep learning
keywords:
  - mxnet
  - python
  - machine
  - learning
home: https://github.com/bitnami/charts/tree/master/bitnami/mxnet
sources:
  - https://github.com/bitnami/bitnami-docker-mxnet
  - https://mxnet.apache.org/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/mxnet/img/mxnet-stack-110x117.png
annotations:
  category: MachineLearning
