apiVersion: v1
name: kubeapps
version: 4.0.3
appVersion: v2.0.0-beta.2
description: Kubeapps is a dashboard for your Kubernetes cluster that makes it easy to deploy and manage applications in your cluster using Helm
icon: https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/img/logo.png
keywords:
  - helm
  - dashboard
  - service catalog
  - deployment
home: https://kubeapps.com
sources:
  - https://github.com/kubeapps/kubeapps
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
annotations:
  category: Infrastructure
