annotations:
  category: ApplicationServer
apiVersion: v2
appVersion: 21.0.1
description: Chart for Wildfly
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/wildfly
icon: https://bitnami.com/assets/stacks/wildfly/img/wildfly-stack-110x117.png
keywords:
  - wildfly
  - java
  - http
  - web
  - application server
  - jsp
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wildfly
sources:
  - https://github.com/bitnami/bitnami-docker-wildfly
  - http://wildfly.org
version: 6.0.2
