{{- if include "osclass.host" . -}}
apiVersion: {{ template "osclass.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "osclass.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "osclass.fullname" . }}
    helm.sh/chart: {{ include "osclass.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "osclass.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "osclass.fullname" . }}
        helm.sh/chart: {{ include "osclass.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
  {{- end }}
  {{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
  {{- end }}
{{- end }}
    spec:
{{- include "osclass.imagePullSecrets" . | indent 6 }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      containers:
      - name: {{ template "osclass.fullname" . }}
        image: {{ template "osclass.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | quote }}
        - name: MARIADB_HOST
          value: {{ include "osclass.databaseHost" . | quote }}
        - name: MARIADB_PORT_NUMBER
          value: {{ include "osclass.databasePort" . | quote }}
        - name: OSCLASS_DATABASE_NAME
          value: {{ include "osclass.databaseName" . | quote }}
        - name: OSCLASS_DATABASE_USER
          value: {{ include "osclass.databaseUser" . | quote }}
        - name: OSCLASS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "osclass.databaseSecretName" . }}
              key: mariadb-password
        {{- $port:=.Values.service.port | toString }}
        - name: OSCLASS_HOST
          value: "{{ include "osclass.host" . }}{{- if ne $port "80" }}:{{ .Values.service.port }}{{ end }}"
        - name: OSCLASS_USERNAME
          value: {{ default "" .Values.osclassUsername | quote }}
        - name: OSCLASS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "osclass.fullname" . }}
              key: osclass-password
        - name: OSCLASS_EMAIL
          value: {{ default "" .Values.osclassEmail | quote }}
        - name: OSCLASS_WEB_TITLE
          value: {{ default "" .Values.osclassWebTitle | quote }}
        - name: OSCLASS_PING_ENGINES
          value: {{ default "" .Values.osclassPingEngines | quote }}
        - name: OSCLASS_SAVE_STATS
          value: {{ default "" .Values.osclassSaveStats | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "osclass.fullname" . }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /index.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "osclass.host" . | quote }}
          initialDelaySeconds: 120
          timeoutSeconds: 120
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /index.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "osclass.host" . | quote }}
          initialDelaySeconds: 30
          timeoutSeconds: 120
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: osclass-data
          mountPath: /bitnami/osclass
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: {{ template "osclass.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        command: [ '/bin/apache_exporter', '--scrape_uri', 'http://status.localhost:80/server-status/?auto']
        ports:
        - name: metrics
          containerPort: 9117
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
  {{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
      volumes:
      - name: osclass-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "osclass.fullname" . }}-osclass
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end -}}
