{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "osclass.fullname" . }}-osclass
  labels:
    app.kubernetes.io/name: {{ include "osclass.fullname" . }}
    helm.sh/chart: {{ include "osclass.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.osclass.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.osclass.size | quote }}
  {{ include "osclass.storageClass" . }}
{{- end -}}
