apiVersion: v1
kind: Secret
metadata:
  name: {{ template "osclass.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "osclass.fullname" . }}
    helm.sh/chart: {{ include "osclass.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.osclassPassword }}
  osclass-password: {{ default "" .Values.osclassPassword | b64enc | quote }}
  {{ else }}
  osclass-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
