{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if $query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-query
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
spec:
  replicas: {{ $query.replicaCount }}
  strategy:
    type: {{ $query.strategyType }}
    {{- if (eq "Recreate" $query.strategyType) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels: {{- include "thanos.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: query
  template:
    metadata:
      labels: {{- include "thanos.labels" . | nindent 8 }}
        app.kubernetes.io/component: query
      {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap $query.podAnnotations }}
      annotations:
        {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
        checksum/ruler-configuration: {{ include (print $.Template.BasePath "/query/sd-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if $query.podAnnotations }}
        {{- include "thanos.tplValue" (dict "value" $query.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
{{- include "thanos.imagePullSecrets" . | nindent 6 }}
      serviceAccount: {{ include "thanos.serviceaccount.name" (dict "component" "query" "context" $) }}
      {{- if $query.affinity }}
      affinity: {{- include "thanos.tplValue" (dict "value" $query.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if $query.nodeSelector }}
      nodeSelector: {{- include "thanos.tplValue" (dict "value" $query.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if $query.tolerations }}
      tolerations: {{- include "thanos.tplValue" (dict "value" $query.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if $query.priorityClassName }}
      priorityClassName: {{ $query.priorityClassName | quote }}
      {{- end }}
      {{- if $query.securityContext.enabled }}
      securityContext:
        runAsUser: {{ $query.securityContext.runAsUser }}
        fsGroup: {{ $query.securityContext.fsGroup }}
      {{- end }}
      containers:
        - name: query
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args:
            - query
            - --log.level={{ $query.logLevel }}
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            {{- if kindIs "string" $query.replicaLabel }}
            - --query.replica-label={{ $query.replicaLabel }}
            {{- else }}
            {{- range $query.replicaLabel }}
            - --query.replica-label={{ . }}
            {{- end }}
            {{- end }}
            {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
            - --store.sd-files=/conf/servicediscovery.yml
            {{- end }}
            {{- if and $query.dnsDiscovery.enabled $query.dnsDiscovery.sidecarsService $query.dnsDiscovery.sidecarsNamespace }}
            - --store=dnssrv+_grpc._tcp.{{- include "thanos.tplValue" ( dict "value" $query.dnsDiscovery.sidecarsService "context" $) -}}.{{- include "thanos.tplValue"  ( dict "value" $query.dnsDiscovery.sidecarsNamespace "context" $) -}}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- if and .Values.storegateway.enabled $query.dnsDiscovery.enabled }}
            - --store=dnssrv+_grpc._tcp.{{ include "thanos.fullname" . }}-storegateway.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- if and .Values.ruler.enabled $query.dnsDiscovery.enabled }}
            - --store=dnssrv+_grpc._tcp.{{ include "thanos.fullname" . }}-ruler.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- range $query.stores }}
            - --store={{ . }}
            {{- end }}
            {{- if $query.grpcTLS.server.secure }}
            - --grpc-server-tls-cert=/tls/server/cert.pem
            - --grpc-server-tls-key=/tls/server/key.pem
            - --grpc-server-tls-client-ca=/tls/server/ca.pem
            {{- end }}
            {{- if $query.grpcTLS.client.secure }}
            - --grpc-client-tls-secure
            {{- if $query.grpcTLS.client.cert }}
            - --grpc-client-tls-cert=/tls/client/cert.pem
            {{- end }}
            {{- if $query.grpcTLS.client.key }}
            - --grpc-client-tls-key=/tls/client/key.pem
            {{- end }}
            {{- if $query.grpcTLS.client.ca }}
            - --grpc-client-tls-ca=/tls/client/ca.pem
            {{- end }}
            {{- if $query.grpcTLS.client.servername }}
            - --grpc-client-server-name={{$query.grpcTLS.client.servername}}
            {{- end }}
            {{- end }}
            {{- if $query.extraFlags }}
            {{- $query.extraFlags | toYaml | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
          {{- if $query.livenessProbe }}
          livenessProbe: {{- include "thanos.tplValue" (dict "value" $query.livenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if $query.readinessProbe }}
          readinessProbe: {{- include "thanos.tplValue" (dict "value" $query.readinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if $query.resources }}
          resources: {{- toYaml $query.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
      {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
            - name: sd-config
              mountPath: /conf/servicediscovery.yml
              subPath: servicediscovery.yml
      {{- end }}
      {{- if $query.grpcTLS.server.secure }}
            - name: tls-server
              mountPath: /tls/server
      {{- end }}
      {{- if $query.grpcTLS.client.secure }}
            - name: tls-client
              mountPath: /tls/client
      {{- end }}
      volumes:
      {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
        - name: sd-config
          configMap:
            name: {{ include "thanos.query.SDConfigmapName" . }}
      {{- end }}
      {{- if $query.grpcTLS.server.secure }}
        - name: tls-server
          secret:
            secretName: {{ include "thanos.fullname" . }}-query-tls-server
      {{- end }}
      {{- if $query.grpcTLS.client.secure }}
        - name: tls-client
          secret:
            secretName: {{ include "thanos.fullname" . }}-query-tls-client
      {{- end }}
{{- end }}
