{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if and $query.enabled $query.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "thanos.fullname" . }}-query
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "thanos.fullname" . }}-query
  minReplicas: {{ $query.autoscaling.minReplicas }}
  maxReplicas: {{ $query.autoscaling.maxReplicas }}
  metrics:
    {{- if $query.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $query.autoscaling.targetCPU }}
    {{- end }}
    {{- if $query.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $query.autoscaling.targetMemory  }}
    {{- end }}
{{- end }}    
