{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if (include "thanos.query.createSDConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}-query-sd-configmap
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
data:
  servicediscovery.yml: |-
    {{- include "thanos.tplValue" (dict "value" $query.sdConfig "context" $) | nindent 4 }}
{{ end }}
