{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if $query.grpcTLS.client.secure -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-query-tls-client
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: query
type: Opaque
data:
{{- if $query.grpcTLS.client.cert }}
  cert.pem: {{ $query.grpcTLS.client.cert | b64enc | quote }}
{{- end }}
{{- if $query.grpcTLS.client.key }}
  key.pem: {{ $query.grpcTLS.client.key | b64enc | quote }}
{{- end }}
{{- if $query.grpcTLS.client.ca }}
  ca.pem : {{ $query.grpcTLS.client.ca | b64enc | quote }}
{{- end }}
{{ end }}
