apiVersion: v1
name: nats
version: 4.5.7
appVersion: 2.1.8
description: An open-source, cloud-native messaging system
keywords:
  - nats
  - messaging
  - addressing
  - discovery
home: https://github.com/bitnami/charts/tree/master/bitnami/nats
sources:
  - https://github.com/bitnami/bitnami-docker-nats
  - https://nats.io/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/nats/img/nats-stack-110x117.png
annotations:
  category: Infrastructure
