annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.1.9
description: An open-source, cloud-native messaging system
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/nats
icon: https://bitnami.com/assets/stacks/nats/img/nats-stack-110x117.png
keywords:
  - nats
  - messaging
  - addressing
  - discovery
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: nats
sources:
  - https://github.com/bitnami/bitnami-docker-nats
  - https://nats.io/
version: 5.0.0
