{{- if and .Values.aggregator.enabled (not .Values.aggregator.configMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-aggregator-cm
  labels: {{- include "fluentd.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
data:
  {{- range $key, $value := .Values.aggregator.configMapFiles }}
  {{ $key }}: |
    {{- include "fluentd.tplValue" (dict "value" $value "context" $) | nindent 4 }}
  {{- end }}
{{- end -}}
