{{- if and .Values.forwarder.enabled (not .Values.forwarder.configMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-forwarder-cm
  labels: {{- include "fluentd.labels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
data:
  {{- range $key, $value := .Values.forwarder.configMapFiles }}
  {{ $key }}: |
    {{- include "fluentd.tplValue" (dict "value" $value "context" $) | nindent 4 }}
  {{- end }}
{{- end -}}
