apiVersion: v1
name: phabricator
version: 9.1.18
appVersion: 2020.42.0
description: Collection of open source web applications that help software companies build better software.
keywords:
  - phabricator
  - http
  - https
  - web
  - application
  - collaboration
  - project management
  - bug tracking
  - code review
  - wiki
  - git
  - mercurial
  - subversion
home: https://github.com/bitnami/charts/tree/master/bitnami/phabricator
sources:
  - https://github.com/bitnami/bitnami-docker-phabricator
  - https://www.phacility.com/phabricator/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/phabricator/img/phabricator-stack-110x117.png
annotations:
  category: ProjectManagement
