{{- if include "suitecrm.host" . -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "suitecrm.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
      {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.podAnnotations }}
      {{- include "common.tplvalues.render" (dict "value" .Values.metrics.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      {{- include "suitecrm.imagePullSecrets" . | nindent 6 }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 8 }}
        {{- end }}
        {{- if and .Values.volumePermissions.enabled .Values.persistence.enabled }}
        - name: volume-permissions
          image: {{ include "suitecrm.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - sh
            - -c
            - |
              mkdir -p "/bitnami/suitecrm"
              chown -R "{{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}" "/bitnami/suitecrm"
          securityContext:
            runAsUser: 0
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: suitecrm-data
              mountPath: /bitnami/suitecrm
              subPath: suitecrm
      {{- end }}
      containers:
        - name: suitecrm
          image: {{ include "suitecrm.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.containerSecurityContext.runAsUser }}
          {{- end }}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: {{ .Values.allowEmptyPassword | quote }}
            - name: SUITECRM_VALIDATE_USER_IP
              value: {{ .Values.suitecrmValidateUserIP | quote }}
            - name: SUITECRM_DATABASE_HOST
              value: {{ include "suitecrm.databaseHost" . | quote }}
            - name: SUITECRM_DATABASE_PORT_NUMBER
              value: {{ include "suitecrm.databasePort" . | quote }}
            - name: MARIADB_HOST
              value: {{ include "suitecrm.databaseHost" . | quote }}
            - name: MARIADB_PORT_NUMBER
              value: {{ include "suitecrm.databasePort" . | quote }}
            - name: SUITECRM_DATABASE_NAME
              value: {{ include "suitecrm.databaseName" . | quote }}
            - name: SUITECRM_DATABASE_USER
              value: {{ include "suitecrm.databaseUser" . | quote }}
            - name: SUITECRM_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "suitecrm.databaseSecretName" . }}
                  key: mariadb-password
            - name: SUITECRM_HOST
              value: {{ include "suitecrm.host" . }}
            - name: SUITECRM_USERNAME
              value: {{ .Values.suitecrmUsername | quote }}
            - name: SUITECRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "suitecrm.fullname" . }}
                  key: suitecrm-password
            - name: SUITECRM_EMAIL
              value: {{ .Values.suitecrmEmail | quote }}
            - name: SUITECRM_SMTP_NOTIFY_NAME
              value: {{ .Values.suitecrmNotifyName | quote }}
            - name: SUITECRM_SMTP_NOTIFY_ADDRESS
              value: {{ .Values.suitecrmNotifyAddress | quote }}
            - name: SUITECRM_SMTP_HOST
              value: {{ .Values.suitecrmSmtpHost | quote }}
            - name: SUITECRM_SMTP_PORT_NUMBER
              value: {{ .Values.suitecrmSmtpPort | quote }}
            - name: SUITECRM_SMTP_USER
              value: {{ .Values.suitecrmSmtpUser | quote }}
            - name: SUITECRM_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "suitecrm.fullname" . }}
                  key: suitecrm-smtp-password
            - name: SUITECRM_SMTP_PROTOCOL
              value: {{ .Values.suitecrmSmtpProtocol | quote }}
            {{- if .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /index.php
              port: http
              httpHeaders:
                - name: Host
                  value: {{ include "suitecrm.host" . | quote }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- else if .Values.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /index.php
              port: http
              httpHeaders:
                - name: Host
                  value: {{ include "suitecrm.host" . | quote }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- else if .Values.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: suitecrm-data
              mountPath: /bitnami/suitecrm
              subPath: suitecrm
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ include "suitecrm.metrics.image" . }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
          command: [ '/bin/apache_exporter', '--scrape_uri', 'http://status.localhost:8080/server-status/?auto']
          ports:
            - name: metrics
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
              timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.resources "context" $) | nindent 12 }}
      {{- end }}
      {{- if .Values.sidecars }}
      {{- include "common.tplvalues.render" (dict "value" .Values.sidecars "context" $) | nindent 8 }}
      {{- end }}
      volumes:
        - name: suitecrm-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "suitecrm.fullname" . }}-suitecrm{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
{{- end -}}
