{{- if and (or (.Files.Glob "files/repmgr.conf") (.Files.Glob "files/postgresql.conf") (.Files.Glob "files/pg_hba.conf") .Values.postgresql.repmgrConfiguration .Values.postgresql.configuration .Values.postgresql.pgHbaConfiguration) (not .Values.postgresql.configurationCM) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "postgresql-ha.postgresql" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if (.Files.Glob "files/repmgr.conf") }}
  {{- (.Files.Glob "files/repmgr.conf").AsConfig | nindent 2 }}
  {{- else if .Values.postgresql.repmgrConfiguration }}
  repmgr.conf: |
  {{- .Values.postgresql.repmgrConfiguration | nindent 4 }}
  {{- end }}
  {{- if (.Files.Glob "files/postgresql.conf") }}
  {{- (.Files.Glob "files/postgresql.conf").AsConfig | nindent 2 }}
  {{- else if .Values.postgresql.configuration }}
  postgresql.conf: |
  {{- range $key, $value := default dict .Values.postgresql.configuration }}
    {{ $key | snakecase }}={{ $value }}
  {{- end }}
  {{- end }}
  {{- if (.Files.Glob "files/pg_hba.conf") }}
  {{- (.Files.Glob "files/pg_hba.conf").AsConfig | nindent 2 }}
  {{- else if .Values.postgresql.pgHbaConfiguration }}
  pg_hba.conf: |
  {{- .Values.postgresql.pgHbaConfiguration | nindent 4 }}
  {{- end }}
{{- end }}
