{{- if and (or (.Files.Glob "files/docker-entrypoint-initdb.d/*.{sh,sql,sql.gz}") .Values.postgresql.initdbScripts) (not .Values.postgresql.initdbScriptsCM) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-initdb-scripts" (include "postgresql-ha.postgresql" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- with .Files.Glob "files/docker-entrypoint-initdb.d/*.sql.gz" }}
binaryData:
{{- range $path, $bytes := . }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc | quote }}
{{- end }}
{{- end }}
data:
  {{- with .Files.Glob "files/docker-entrypoint-initdb.d/*.{sh,sql}" }}
  {{- .AsConfig | nindent 2 }}
  {{- end }}
  {{- with .Values.postgresql.initdbScripts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
