{{- if .Values.querier.grpcTLS.client.secure -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-querier-tls-client
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
type: Opaque
data:
{{- if .Values.querier.grpcTLS.client.cert }}
  cert.pem: {{ .Values.querier.grpcTLS.client.cert | b64enc | quote }}
{{- end }}
{{- if .Values.querier.grpcTLS.client.key }}
  key.pem: {{ .Values.querier.grpcTLS.client.key | b64enc | quote }}
{{- end }}
{{- if .Values.querier.grpcTLS.client.ca }}
  ca.pem : {{ .Values.querier.grpcTLS.client.ca | b64enc | quote }}
{{- end }}
{{ end }}
