dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
