apiVersion: v1
name: phpbb
version: 8.0.0
appVersion: 3.3.1
description: Community forum that supports the notion of users and groups, file attachments, full-text search, notifications and more.
keywords:
  - phpbb
  - forum
  - http
  - php
home: https://github.com/bitnami/charts/tree/master/bitnami/phpbb
icon: https://bitnami.com/assets/stacks/phpbb/img/phpbb-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-phpbb
  - https://www.phpbb.com/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: Forum
