magentoHost: magento.local
service:
  type: ClusterIP
ingress:
  enabled: true
  tls: true
  hostname: magento.local
livenessProbe:
  httpGet:
    httpHeaders: []
readinessProbe:
  httpGet:
    httpHeaders: []
