magentoHost: magento.local
mariadb:
  enabled: false
externalDatabase:
  host: database.local
metrics:
  enabled: true
ingress:
  enabled: true
livenessProbe:
  httpGet:
    httpHeaders: []
readinessProbe:
  httpGet:
    httpHeaders: []
