apiVersion: v1
name: magento
version: 14.0.6
appVersion: 2.4.1
description: A feature-rich flexible e-commerce solution. It includes transaction options, multi-store functionality, loyalty programs, product categorization and shopper filtering, promotion rules, and more.
keywords:
  - magento
  - e-commerce
  - http
  - web
  - php
home: https://github.com/bitnami/charts/tree/master/bitnami/magento
sources:
  - https://github.com/bitnami/bitnami-docker-magento
  - https://magento.com/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-110x117.png
annotations:
  category: E-Commerce
