{{- if include "owncloud.host" . -}}
apiVersion: {{ template "owncloud.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "owncloud.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "owncloud.fullname" . }}
    helm.sh/chart: {{ include "owncloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "owncloud.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  replicas: 1
{{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "owncloud.fullname" . }}
        helm.sh/chart: {{ include "owncloud.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
  {{- end }}
  {{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
  {{- end }}
{{- end }}
    spec:
{{- include "owncloud.imagePullSecrets" . | indent 6 }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      initContainers:
      {{- include "certificates.initContainer" . | indent 8 }}
      containers:
      - name: {{ template "owncloud.fullname" . }}
        image: {{ template "owncloud.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | quote }}
        - name: MARIADB_HOST
          value: {{ include "owncloud.databaseHost" . | quote }}
        - name: MARIADB_PORT_NUMBER
          value: {{ include "owncloud.databasePort" . | quote }}
        - name: OWNCLOUD_DATABASE_NAME
          value: {{ include "owncloud.databaseName" . | quote }}
        - name: OWNCLOUD_DATABASE_USER
          value: {{ include "owncloud.databaseUser" . | quote }}
        - name: OWNCLOUD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "owncloud.databaseSecretName" . }}
              key: mariadb-password
{{- $port:=.Values.service.port | toString }}
        - name: OWNCLOUD_HOST
          value: "{{ include "owncloud.host" . }}{{- if ne $port "80" }}:{{ .Values.service.port }}{{ end }}"
        - name: OWNCLOUD_USERNAME
          value: {{ default "" .Values.owncloudUsername | quote }}
        - name: OWNCLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "owncloud.fullname" . }}
              key: owncloud-password
        - name: OWNCLOUD_EMAIL
          value: {{ default "" .Values.owncloudEmail | quote }}
        {{- if .Values.extraEnvVars }}
        {{- include "owncloud.tplValues.render" ( dict "value" .Values.extraEnvVars "context" $ ) | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "owncloud.host" . | quote }}
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "owncloud.host" . | quote }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        {{- include "certificates.volumeMount" . | indent 8 }}
        - name: owncloud-data
          mountPath: /bitnami/owncloud
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: {{ template "owncloud.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        command: [ '/bin/apache_exporter', '--scrape_uri', 'http://status.localhost:80/server-status/?auto']
        ports:
        - name: metrics
          containerPort: 9117
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
  {{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
      volumes:
      {{- include "certificates.volumes" . | indent 6 }}
      - name: owncloud-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.owncloud.existingClaim }}{{ .Values.persistence.owncloud.existingClaim }}{{- else }}{{ template "owncloud.fullname" . }}-owncloud{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end -}}
