{{- if (not (or .Values.mariadb.enabled .Values.externalDatabase.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app.kubernetes.io/name: {{ include "owncloud.fullname" . }}
    helm.sh/chart: {{ include "owncloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  mariadb-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
