apiVersion: v1
kind: Secret
metadata:
  name: {{ template "owncloud.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "owncloud.fullname" . }}
    helm.sh/chart: {{ include "owncloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.owncloudPassword }}
  owncloud-password: {{ .Values.owncloudPassword | b64enc | quote }}
  {{ else }}
  owncloud-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
