dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: kube-state-metrics
    repository: https://charts.bitnami.com/bitnami
    version: 0.x.x
    condition: kube-state-metrics.enabled
