dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: mariadb
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
    tags:
      - ejbca-database
