apiVersion: v1
kind: Service
metadata:
  name: {{ template "phpmyadmin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "phpmyadmin.fullname" . }}
    helm.sh/chart: {{ include "phpmyadmin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "phpmyadmin.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
