apiVersion: v1
name: joomla
version: 8.1.8
appVersion: 3.9.22
description: PHP content management system (CMS) for publishing web content
keywords:
  - joomla
  - cms
  - blog
  - http
  - php
home: https://github.com/bitnami/charts/tree/master/bitnami/joomla
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-joomla
  - http://www.joomla.org/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: CMS
