apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orangehrm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "orangehrm.fullname" . }}
    helm.sh/chart: {{ include "orangehrm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.orangehrmPassword }}
  orangehrm-password: {{ default "" .Values.orangehrmPassword | b64enc | quote }}
  {{ else }}
  orangehrm-password: {{ list (lower (randAlpha 3)) (randNumeric 2) (upper (randAlpha 3)) | join "_" | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
