dependencies:
  - name: mariadb
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: common
    version: 0.8.x
    repository: https://charts.bitnami.com/bitnami
