apiVersion: v1
name: postgresql-ha
version: 5.0.0
appVersion: 11.9.1
description: Chart for PostgreSQL with HA architecture (using Replication Manager (repmgr) and Pgpool).
keywords:
  - postgresql
  - repmgr
  - pgpool
  - postgres
  - database
  - sql
  - replication
  - cluster
  - high availability
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
sources:
  - https://github.com/bitnami/bitnami-docker-postgresql
  - https://www.postgresql.org/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: Database
