apiVersion: v1
name: fluentd
version: 2.4.0
appVersion: 1.11.4
description: Fluentd is an open source data collector for unified logging layer
keywords:
  - fluentd
  - logging
  - logs
  - data
  - collector
home: https://github.com/bitnami/charts/tree/master/bitnami/fluentd
sources:
  - https://github.com/bitnami/bitnami-docker-fluentd
  - https://www.fluentd.org/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/fluentd/img/fluentd-stack-110x117.png
annotations:
  category: Analytics
