{{- if (not (or .Values.mariadb.enabled .Values.externalDatabase.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.externalDatabase.rootPassword | b64enc | quote }}
{{- end }}
