dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: SUBCHART_NAME
    repository: https://charts.bitnami.com/bitnami
    version: %%MAJOR_SUBCHART_VERSION_(A.X.X)%%
    condition: SUBCHART_NAME.enabled
