apiVersion: {{ template "jasperreports.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "jasperreports.fullname" . }}
  labels:
    app.kubernetes.io/name: "{{ include "jasperreports.fullname" . }}"
    helm.sh/chart: "{{ include "jasperreports.chart" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "jasperreports.fullname" . }}"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "jasperreports.fullname" . }}"
        helm.sh/chart: "{{ include "jasperreports.chart" . }}"
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      {{- include "jasperreports.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "jasperreports.fullname" . }}
          image: {{ template "jasperreports.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: {{ .Values.allowEmptyPassword | quote }}
            - name: MARIADB_HOST
              value: {{ include "jasperreports.databaseHost" . | quote }}
            - name: MARIADB_PORT_NUMBER
              value: {{ include "jasperreports.databasePort" . | quote }}
            - name: JASPERREPORTS_DATABASE_NAME
              value: {{ include "jasperreports.databaseName" . | quote }}
            - name: JASPERREPORTS_DATABASE_USER
              value: {{ include "jasperreports.databaseUser" . | quote }}
            - name: JASPERREPORTS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jasperreports.databaseSecretName" . }}
                  key: mariadb-password
            - name: JASPERREPORTS_USERNAME
              value: {{ .Values.jasperreportsUsername | quote }}
            - name: JASPERREPORTS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jasperreports.fullname" . }}
                  key: jasperreports-password
            - name: JASPERREPORTS_EMAIL
              value: {{ .Values.jasperreportsEmail | quote }}
            {{- if .Values.smtpHost }}
            - name: SMTP_HOST
              value: {{ .Values.smtpHost | quote }}
            {{- end }}
            {{- if .Values.smtpPort }}
            - name: SMTP_PORT
              value: {{ .Values.smtpPort | quote }}
            {{- end }}
            {{- if .Values.smtpEmail }}
            - name: SMTP_EMAIL
              value: {{ .Values.smtpEmail| quote }}
            {{- end }}
            {{- if .Values.smtpUser }}
            - name: SMTP_USER
              value: {{ .Values.smtpUser | quote }}
            {{- end }}
            {{- if .Values.smtpPassword }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jasperreports.fullname" . }}
                  key: smtp-password
            {{- end }}
            {{- if .Values.smtpProtocol }}
            - name: SMTP_PROTOCOL
              value: {{ .Values.smtpProtocol | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /jasperserver/login.html
              port: http
            initialDelaySeconds: 300
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /jasperserver/login.html
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: jasperreports-data
              mountPath: /bitnami/jasperreports
      volumes:
        - name: jasperreports-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "jasperreports.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
