{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jasperreports.fullname" . }}
  labels:
    app.kubernetes.io/name: "{{ include "jasperreports.fullname" . }}"
    helm.sh/chart: "{{ include "jasperreports.chart" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          serviceName: {{ template "jasperreports.fullname" $ }}
          servicePort: http
  {{- end }}
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
  {{- if .tlsHosts }}
  {{- range $host := .tlsHosts }}
    - {{ $host }}
  {{- end }}
  {{- else }}
    - {{ .name }}
  {{- end }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  {{- end }}
{{- end }}
