{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jasperreports.fullname" . }}
  labels:
    app.kubernetes.io/name: "{{ include "jasperreports.fullname" . }}"
    helm.sh/chart: "{{ include "jasperreports.chart" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "jasperreports.storageClass" . }}
{{- end -}}
