apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-env-vars" (include "keycloak.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.adminPassword }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- else }}
  KEYCLOAK_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.managementPassword }}
  KEYCLOAK_MANAGEMENT_PASSWORD: {{ .Values.auth.managementPassword | b64enc | quote }}
  {{- else }}
  KEYCLOAK_MANAGEMENT_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  KEYCLOAK_DATABASE_PASSWORD: {{ include "keycloak.databaseEncryptedPassword" . }}
  {{- if .Values.auth.tls.enabled }}
  {{- if .Values.auth.tls.keystorePassword }}
  KEYCLOAK_TLS_KEYSTORE_PASSWORD: {{ .Values.auth.tls.keystorePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.tls.truststorePassword }}
  KEYCLOAK_TLS_TRUSTSTORE_PASSWORD: {{ .Values.auth.tls.truststorePassword | b64enc | quote }}
  {{- end }}
  {{- end }}
