{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "airflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "airflow.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "airflow.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "airflow.tplValue" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
{{- end -}}

