{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "airflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "airflow.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "airflow.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "airflow.tplValue" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "airflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "airflow.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
