apiVersion: v1
name: redmine
version: 14.2.11
appVersion: 4.1.1
description: A flexible project management web application.
keywords:
  - redmine
  - project management
  - www
  - http
  - web
  - application
  - ruby
  - rails
home: https://github.com/bitnami/charts/tree/master/bitnami/redmine
icon: https://bitnami.com/assets/stacks/redmine/img/redmine-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-redmine
  - http://www.redmine.org/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: ProjectManagement
